name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist  # Vite outputs to the "dist" folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
